Repository tuanngo1001/tubtrunk, pull requests merged in 2021-03, with the labels that each got.

#83 Change gif to local
  source/tubtrunk/assets/gifs/alreadyexist.gif
  source/tubtrunk/assets/gifs/errorwarning.gif
  source/tubtrunk/assets/gifs/giftrecieve.gif
  source/tubtrunk/assets/gifs/logoutfail.gif
  source/tubtrunk/assets/gifs/money.gif
  source/tubtrunk/assets/gifs/passwordwarning.gif
  source/tubtrunk/assets/gifs/purchaseprompt.gif
  source/tubtrunk/assets/gifs/welcome.gif
  source/tubtrunk/assets/gifs/yournameis.gif
  source/tubtrunk/lib/Views/notificationView.dart
  source/tubtrunk/pubspec.yaml
Labels: bug

#86 Add unit test for coupon model
  source/tubtrunk/lib/Models/petModel.dart
  source/tubtrunk/test/model_tests/coupon_model_test.dart
Labels: testing

#88 Add FAB to share any chosen achievement
  source/tubtrunk/lib/Views/missionView.dart
Labels: user story

#89 Fix FAB, change to be able to share all tab in Mission View
  source/tubtrunk/lib/Views/missionView.dart
Labels: bug

#94 Mission tests
  Diagrams/Class_Diagram.png
  source/tubtrunk/lib/Controllers/rewardMissionController.dart
  source/tubtrunk/lib/Models/rewardMissionModel.dart
  source/tubtrunk/lib/Views/missionView.dart
  source/tubtrunk/test/controller_tests/reward_mission_controller_test.dart
  source/tubtrunk/test/controller_tests/reward_mission_controller_test.mocks.dart
  source/tubtrunk/test/model_tests/reward_mission_model_test.dart
Labels: testing
